create table if not exists analytics_events (
    id bigint generated by default as identity primary key,
    event_type varchar(64) not null,
    subject_id varchar(64) not null,
    details varchar(255) not null
);
