package com.example.demo.analytics;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Writes simple operational events to a secondary database.
 */
@Component
public class AnalyticsEventStore {

    private final JdbcTemplate analyticsJdbcTemplate;

    public AnalyticsEventStore(JdbcTemplate analyticsJdbcTemplate) {
        this.analyticsJdbcTemplate = analyticsJdbcTemplate;
        this.analyticsJdbcTemplate.execute("""
                create table if not exists analytics_events (
                    id bigint generated by default as identity primary key,
                    event_type varchar(64) not null,
                    subject_id varchar(64) not null,
                    details varchar(255) not null
                )
                """);
    }

    /**
     * Persists an analytics event.
     *
     * @param eventType event classification
     * @param subjectId related entity identifier
     * @param details free-form summary for the demo
     */
    public void record(String eventType, String subjectId, String details) {
        analyticsJdbcTemplate.update(
                "insert into analytics_events(event_type, subject_id, details) values (?, ?, ?)",
                eventType,
                subjectId,
                details
        );
    }

    public int countEvents() {
        Integer count = analyticsJdbcTemplate.queryForObject("select count(*) from analytics_events", Integer.class);
        return count == null ? 0 : count;
    }
}
