create table outbox_events (
    id bigint generated by default as identity primary key,
    aggregate_type varchar(80) not null,
    aggregate_id varchar(120) not null,
    event_type varchar(120) not null,
    payload text not null,
    status varchar(32) not null,
    attempts integer not null default 0,
    available_at timestamp not null,
    created_at timestamp not null,
    published_at timestamp null,
    last_error varchar(1000) null
);

create index idx_outbox_events_status_available_at on outbox_events(status, available_at);
