spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/usersdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

app.analytics.datasource.url=${APP_ANALYTICS_DATASOURCE_URL:jdbc:postgresql://localhost:15433/analyticsdb}
app.analytics.datasource.driver-class-name=org.postgresql.Driver
app.analytics.datasource.username=${APP_ANALYTICS_DATASOURCE_USERNAME:postgres}
app.analytics.datasource.password=${APP_ANALYTICS_DATASOURCE_PASSWORD:postgres}

spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=validate

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
